package monsters

import "github.com/usagiga/pathfinder-dqm3/common"

var (
	Monsters = []common.Monster{
		{
			ID:     1,
			Name:   "スライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     2,
			Name:   "スライムコロネ",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     3,
			Name:   "スライムつむり",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     4,
			Name:   "スライムツリー",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     5,
			Name:   "パールスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     6,
			Name:   "はねスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     7,
			Name:   "バブルスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     8,
			Name:   "ホイミスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     9,
			Name:   "マッシュスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     10,
			Name:   "マンドラ",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     11,
			Name:   "ジャングラー",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     12,
			Name:   "スノーム",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     13,
			Name:   "スライムカルゴ",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     14,
			Name:   "スライムタワー",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     15,
			Name:   "スライムナイト",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     16,
			Name:   "スライムベス",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     17,
			Name:   "たまねぎスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     18,
			Name:   "ドラゴスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     19,
			Name:   "ぶちスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     20,
			Name:   "ボックススライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_F,
		},
		{
			ID:     21,
			Name:   "アラウネ",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     22,
			Name:   "エンゼルスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     23,
			Name:   "こんぺいとう",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     24,
			Name:   "ストーンスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     25,
			Name:   "スピンスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     26,
			Name:   "スライムタール",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     27,
			Name:   "ダークスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     28,
			Name:   "ぬかどこスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     29,
			Name:   "メタルスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     30,
			Name:   "もりもりスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_E,
		},
		{
			ID:     31,
			Name:   "キングスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     32,
			Name:   "スライムファング",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     33,
			Name:   "スライムブレス",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     34,
			Name:   "石炭つむり",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     35,
			Name:   "ダークキング",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     36,
			Name:   "チョコタワー",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     37,
			Name:   "つららスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     38,
			Name:   "バブルキング",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     39,
			Name:   "ベホマスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     40,
			Name:   "もりもりベス",
			Family: common.Family_Slime,
			Rank:   common.Rank_D,
		},
		{
			ID:     41,
			Name:   "コロネホワイト",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     42,
			Name:   "スライムジョーカー",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     43,
			Name:   "スライムダーク",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     44,
			Name:   "スライムフェアリー",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     45,
			Name:   "スライムプディング",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     46,
			Name:   "スライムボーグ",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     47,
			Name:   "はぐれメタル",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     48,
			Name:   "ぶちスライムベス",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     49,
			Name:   "メタルライダー",
			Family: common.Family_Slime,
			Rank:   common.Rank_C,
		},
		{
			ID:     50,
			Name:   "キングジョーカー",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     51,
			Name:   "クイーンスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     52,
			Name:   "クリスタルスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     53,
			Name:   "スライムジェネラル",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     54,
			Name:   "スライムベホマズン",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     55,
			Name:   "タールキング",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     56,
			Name:   "だんごスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     57,
			Name:   "ふうらいスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     58,
			Name:   "メタルキング",
			Family: common.Family_Slime,
			Rank:   common.Rank_B,
		},
		{
			ID:     59,
			Name:   "ゴールデンスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_A,
		},
		{
			ID:     60,
			Name:   "ゴッドライダー",
			Family: common.Family_Slime,
			Rank:   common.Rank_A,
		},
		{
			ID:     61,
			Name:   "スライムエンペラー",
			Family: common.Family_Slime,
			Rank:   common.Rank_A,
		},
		{
			ID:     62,
			Name:   "マスタースライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_A,
		},
		{
			ID:     63,
			Name:   "グランスライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_S,
		},
		{
			ID:     64,
			Name:   "いっかく竜",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     65,
			Name:   "いばらドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     66,
			Name:   "コドラ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     67,
			Name:   "ドラゴンキッズ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     68,
			Name:   "はじけドーラ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     69,
			Name:   "はなまきドラゴ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     70,
			Name:   "フェアリードラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     71,
			Name:   "プテラノドン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     72,
			Name:   "ポイズンリザード",
			Family: common.Family_Dragon,
			Rank:   common.Rank_G,
		},
		{
			ID:     73,
			Name:   "アイアンタートル",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     74,
			Name:   "ウィングスネーク",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     75,
			Name:   "クロコマーチ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     76,
			Name:   "シーホース",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     78,
			Name:   "スマイルリザード",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     79,
			Name:   "ダッシュラン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     80,
			Name:   "デンデン竜",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     81,
			Name:   "ワイバーンドッグ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     77,
			Name:   "スカイドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_F,
		},
		{
			ID:     82,
			Name:   "ガメゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     83,
			Name:   "ギガントヒルズ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     84,
			Name:   "ソードドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     85,
			Name:   "デンタザウルス",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     86,
			Name:   "毒つぼドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     87,
			Name:   "ドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     88,
			Name:   "フーセンドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     89,
			Name:   "フォレストドラゴ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     90,
			Name:   "リザードマン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_E,
		},
		{
			ID:     91,
			Name:   "アックスドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     92,
			Name:   "アルゴングレート",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     93,
			Name:   "スノードラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     94,
			Name:   "せつげんりゅう",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     95,
			Name:   "ドラゴンポップ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     96,
			Name:   "ドラゴンライダー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     97,
			Name:   "ヘルダイバー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     98,
			Name:   "メタルドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     99,
			Name:   "ライバーン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_D,
		},
		{
			ID:     100,
			Name:   "ウルフドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     101,
			Name:   "ガメゴンロード",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     102,
			Name:   "キングリザード",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     103,
			Name:   "コアトル",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     104,
			Name:   "シャンタク",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     105,
			Name:   "バザックス",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     106,
			Name:   "バルンバ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     107,
			Name:   "ボボンガー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     108,
			Name:   "ワニバーン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_C,
		},
		{
			ID:     109,
			Name:   "ギガントドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     110,
			Name:   "グレイトドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     111,
			Name:   "シュプリンガー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     112,
			Name:   "ハデスナイト",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     113,
			Name:   "バトルレックス",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     114,
			Name:   "フールフール",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     115,
			Name:   "ブラックドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     116,
			Name:   "やまたのおろち",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     117,
			Name:   "ランドアーマー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_B,
		},
		{
			ID:     118,
			Name:   "アンドレアル",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     119,
			Name:   "カイザードラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     120,
			Name:   "キングヒドラ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     121,
			Name:   "クームヤーガ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     122,
			Name:   "サラマンダー",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     123,
			Name:   "シルバーナーガ",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     124,
			Name:   "ダースドラゴン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     125,
			Name:   "ひかりの番人",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     126,
			Name:   "メカバーン",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     127,
			Name:   "りゅうおう",
			Family: common.Family_Dragon,
			Rank:   common.Rank_A,
		},
		{
			ID:     128,
			Name:   "グレイナル",
			Family: common.Family_Dragon,
			Rank:   common.Rank_S,
		},
		{
			ID:     129,
			Name:   "じげんりゅう",
			Family: common.Family_Dragon,
			Rank:   common.Rank_S,
		},
		{
			ID:     130,
			Name:   "ドラゴンアビス",
			Family: common.Family_Dragon,
			Rank:   common.Rank_S,
		},
		{
			ID:     131,
			Name:   "闇竜バルボロス",
			Family: common.Family_Dragon,
			Rank:   common.Rank_S,
		},
		{
			ID:     132,
			Name:   "竜王",
			Family: common.Family_Dragon,
			Rank:   common.Rank_S,
		},
		{
			ID:     133,
			Name:   "しんりゅう",
			Family: common.Family_Dragon,
			Rank:   common.Rank_X,
		},
		{
			ID:     134,
			Name:   "竜神王",
			Family: common.Family_Dragon,
			Rank:   common.Rank_X,
		},
		{
			ID:     135,
			Name:   "おおがらす",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     136,
			Name:   "おおにわとり",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     137,
			Name:   "オニオーン",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     138,
			Name:   "キャタピラー",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     139,
			Name:   "くしざしツインズ",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     140,
			Name:   "ズッキーニャ",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     141,
			Name:   "テールイーター",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     142,
			Name:   "ナスビナーラ",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     143,
			Name:   "ピッキー",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     144,
			Name:   "プチアーノン",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     145,
			Name:   "フロッガー",
			Family: common.Family_Nature,
			Rank:   common.Rank_G,
		},
		{
			ID:     146,
			Name:   "あばれうしどり",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     147,
			Name:   "オクトリーチ",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     148,
			Name:   "かまいたち",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     149,
			Name:   "ガルーダ",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     150,
			Name:   "キラーコーン",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     151,
			Name:   "サボテンボール",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     152,
			Name:   "タップペンギー",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     153,
			Name:   "どんぐりベビー",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     154,
			Name:   "はさみくわがた",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     155,
			Name:   "ミノーン",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     156,
			Name:   "もみじこぞう",
			Family: common.Family_Nature,
			Rank:   common.Rank_F,
		},
		{
			ID:     157,
			Name:   "イルカちょうちん",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     158,
			Name:   "キメラ",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     159,
			Name:   "キラービー",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     160,
			Name:   "ぐんたいガニ",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     161,
			Name:   "タコメット",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     162,
			Name:   "デザートランナー",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     163,
			Name:   "デッドペッカー",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     164,
			Name:   "とつげきうお",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     165,
			Name:   "ビーンファイター",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     166,
			Name:   "ヘルボックル",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     167,
			Name:   "メランザーナ",
			Family: common.Family_Nature,
			Rank:   common.Rank_E,
		},
		{
			ID:     168,
			Name:   "岩とびあくま",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     169,
			Name:   "うずしおキング",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     170,
			Name:   "エビルアングラー",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     171,
			Name:   "ガマキャノン",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     172,
			Name:   "サンダーフロッグ",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     173,
			Name:   "じごくのたまねぎ",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     174,
			Name:   "スノーグリフォン",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     175,
			Name:   "ダンジョンえび",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     176,
			Name:   "トドマン",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     177,
			Name:   "ひとくいそう",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     178,
			Name:   "ヘルコンドル",
			Family: common.Family_Nature,
			Rank:   common.Rank_D,
		},
		{
			ID:     179,
			Name:   "アンズー",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     180,
			Name:   "かえんムカデ",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     181,
			Name:   "ケセランパセラン",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     182,
			Name:   "さそりアーマー",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     183,
			Name:   "じごくのハサミ",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     184,
			Name:   "だいおうイカ",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     185,
			Name:   "だいおうガマ",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     186,
			Name:   "ダンスニードル",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     187,
			Name:   "ブラックベジター",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     188,
			Name:   "レッドシャモ",
			Family: common.Family_Nature,
			Rank:   common.Rank_C,
		},
		{
			ID:     189,
			Name:   "アカイライ",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     190,
			Name:   "荒野シュリンプ",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     191,
			Name:   "スターキメラ",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     192,
			Name:   "ニードルフィン",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     193,
			Name:   "ひくいどり",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     194,
			Name:   "ブラッドオックス",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     195,
			Name:   "ブルベリーノ",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     196,
			Name:   "ホエールマージ",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     197,
			Name:   "ホークブリザード",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     198,
			Name:   "ロックちょう",
			Family: common.Family_Nature,
			Rank:   common.Rank_B,
		},
		{
			ID:     199,
			Name:   "クラーゴン",
			Family: common.Family_Nature,
			Rank:   common.Rank_A,
		},
		{
			ID:     200,
			Name:   "ほうおう",
			Family: common.Family_Nature,
			Rank:   common.Rank_A,
		},
		{
			ID:     201,
			Name:   "メタルスコーピオン",
			Family: common.Family_Nature,
			Rank:   common.Rank_A,
		},
		{
			ID:     202,
			Name:   "ローズバトラー",
			Family: common.Family_Nature,
			Rank:   common.Rank_A,
		},
		{
			ID:     203,
			Name:   "にじくじゃく",
			Family: common.Family_Nature,
			Rank:   common.Rank_S,
		},
		{
			ID:     204,
			Name:   "ロイヤルブルーム",
			Family: common.Family_Nature,
			Rank:   common.Rank_S,
		},
		{
			ID:     205,
			Name:   "アントベア",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     206,
			Name:   "いたずらもぐら",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     207,
			Name:   "いっかくうさぎ",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     208,
			Name:   "おおきづち",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     209,
			Name:   "おおねずみ",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     210,
			Name:   "コサックシープ",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     211,
			Name:   "しましまキャット",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     212,
			Name:   "ビッグハット",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     213,
			Name:   "ファーラット",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     214,
			Name:   "ベビーパンサー",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     215,
			Name:   "みみとびねずみ",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     216,
			Name:   "ももんじゃ",
			Family: common.Family_Beast,
			Rank:   common.Rank_G,
		},
		{
			ID:     217,
			Name:   "イエティ",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     218,
			Name:   "オーク",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     219,
			Name:   "キャットフライ",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     220,
			Name:   "スカルガルー",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     221,
			Name:   "とらおとこ",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     222,
			Name:   "ぬすっとウサギ",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     223,
			Name:   "ひぐれバット",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     224,
			Name:   "ホークマン",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     225,
			Name:   "ポンポコだぬき",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     226,
			Name:   "ゆめにゅうどう",
			Family: common.Family_Beast,
			Rank:   common.Rank_F,
		},
		{
			ID:     227,
			Name:   "アルミラージ",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     228,
			Name:   "エビルハムスター",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     229,
			Name:   "かくとうパンサー",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     230,
			Name:   "グリズリー",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     231,
			Name:   "シャドウベビー",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     232,
			Name:   "ダックスビル",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     233,
			Name:   "トンブレロ",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     234,
			Name:   "ねこまどう",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     235,
			Name:   "ビックアイ",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     236,
			Name:   "ブラウニー",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     237,
			Name:   "プリズニャン",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     238,
			Name:   "モコモコじゅう",
			Family: common.Family_Beast,
			Rank:   common.Rank_E,
		},
		{
			ID:     239,
			Name:   "あらくれチャッピー",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     240,
			Name:   "ウイングタイガー",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     241,
			Name:   "ガーゴイル",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     242,
			Name:   "キラーパンサー",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     243,
			Name:   "ジラフマスター",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     244,
			Name:   "ソルジャーブル",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     245,
			Name:   "デザートゴースト",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     246,
			Name:   "トロピカキング",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     247,
			Name:   "ベンガル",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     248,
			Name:   "ユニコーン",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     249,
			Name:   "よるのていおう",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     250,
			Name:   "ライノソルジャー",
			Family: common.Family_Beast,
			Rank:   common.Rank_D,
		},
		{
			ID:     251,
			Name:   "アームライオン",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     252,
			Name:   "アバランチャー",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     253,
			Name:   "オークキング",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     254,
			Name:   "キラーピッケル",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     255,
			Name:   "ダンビラムーチョ",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     256,
			Name:   "ビッグももんじゃ",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     257,
			Name:   "ブラバニクイーン",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     258,
			Name:   "まかいじゅう",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     259,
			Name:   "マムー",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     260,
			Name:   "ムーンフェイス",
			Family: common.Family_Beast,
			Rank:   common.Rank_C,
		},
		{
			ID:     261,
			Name:   "ゲリュオン",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     262,
			Name:   "シャドウパンサー",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     263,
			Name:   "ダークペルシャ",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     264,
			Name:   "ダースリカント",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     265,
			Name:   "とうだいタイガー",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     266,
			Name:   "ドン・モグーラ",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     267,
			Name:   "バッファロン",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     268,
			Name:   "ベロリンマン",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     269,
			Name:   "モヒカント",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     270,
			Name:   "れんごく天馬",
			Family: common.Family_Beast,
			Rank:   common.Rank_B,
		},
		{
			ID:     271,
			Name:   "キャット・リベリオ",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     273,
			Name:   "黒竜丸",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     274,
			Name:   "心眼たぬき",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     275,
			Name:   "デスゴーゴン",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     276,
			Name:   "ネンガル",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     277,
			Name:   "魔犬レオパルド",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     278,
			Name:   "ももいろキング",
			Family: common.Family_Beast,
			Rank:   common.Rank_S,
		},
		{
			ID:     272,
			Name:   "キングレオ",
			Family: common.Family_Beast,
			Rank:   common.Rank_A,
		},
		{
			ID:     279,
			Name:   "からくりエッグ",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     280,
			Name:   "ギズモ",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     281,
			Name:   "くみひもこぞう",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     282,
			Name:   "シャイニング",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     283,
			Name:   "たけやりへい",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     284,
			Name:   "ドロザラー",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     285,
			Name:   "どろにんぎょう",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     286,
			Name:   "フォンデュ",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     287,
			Name:   "メタッピー",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     288,
			Name:   "ランタンこぞう",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     289,
			Name:   "わらいぶくろ",
			Family: common.Family_Material,
			Rank:   common.Rank_G,
		},
		{
			ID:     290,
			Name:   "あばれこまいぬ",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     291,
			Name:   "おばけプレート",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     292,
			Name:   "チョコゴーレム",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     293,
			Name:   "とげジョボー",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     294,
			Name:   "ドラムゴート",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     295,
			Name:   "トルトリーナ",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     296,
			Name:   "ドロヌーバ",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     297,
			Name:   "ひとくいサーベル",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     298,
			Name:   "ひとくいばこ",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     299,
			Name:   "ミステリドール",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     300,
			Name:   "メタルハンター",
			Family: common.Family_Material,
			Rank:   common.Rank_F,
		},
		{
			ID:     301,
			Name:   "いどまじん",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     302,
			Name:   "エンタシスマン",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     303,
			Name:   "おどるほうせき",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     304,
			Name:   "ガチャコッコ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     305,
			Name:   "キラーアンブレラ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     306,
			Name:   "クリオネオン",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     307,
			Name:   "ケミカルゼリー",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     308,
			Name:   "シールドオーガ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     309,
			Name:   "デビルアーマー",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     310,
			Name:   "ばくだんいわ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     311,
			Name:   "ヒートギズモ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     312,
			Name:   "フロストギズモ",
			Family: common.Family_Material,
			Rank:   common.Rank_E,
		},
		{
			ID:     313,
			Name:   "キラーマシン",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     314,
			Name:   "サブナック",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     315,
			Name:   "シーゴーレム",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     316,
			Name:   "しびれだんびら",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     317,
			Name:   "ストーンマン",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     318,
			Name:   "デビルスノー",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     319,
			Name:   "ハニーイーター",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     320,
			Name:   "ひょうがまじん",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     321,
			Name:   "ふくぶくろ",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     322,
			Name:   "ブリザード",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     323,
			Name:   "フレイム",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     324,
			Name:   "ようがんまじん",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
		{
			ID:     325,
			Name:   "うごくせきぞう",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     326,
			Name:   "おうのはかもり",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     327,
			Name:   "スウィートバッグ",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     328,
			Name:   "デスソーサー",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     329,
			Name:   "なげきムーン",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     330,
			Name:   "ブリザードマン",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     331,
			Name:   "ほのおのせんし",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     332,
			Name:   "ホワイトビート",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     333,
			Name:   "ミミック",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     334,
			Name:   "メガザルロック",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     335,
			Name:   "ルバンカ",
			Family: common.Family_Material,
			Rank:   common.Rank_C,
		},
		{
			ID:     336,
			Name:   "からくりだいみょう",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     337,
			Name:   "ギャスモン",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     338,
			Name:   "グレイトボンバー",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     339,
			Name:   "ゴールデンゴーレム",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     340,
			Name:   "ゴーレム",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     341,
			Name:   "サタンメイル",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     342,
			Name:   "ジェリーマン",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     343,
			Name:   "スノーホムンクルス",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     344,
			Name:   "デスホール",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     345,
			Name:   "デュランダル",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     346,
			Name:   "ヘルシーサー",
			Family: common.Family_Material,
			Rank:   common.Rank_B,
		},
		{
			ID:     347,
			Name:   "キラーマシン2",
			Family: common.Family_Material,
			Rank:   common.Rank_A,
		},
		{
			ID:     348,
			Name:   "Sキラーマシン",
			Family: common.Family_Material,
			Rank:   common.Rank_A,
		},
		{
			ID:     349,
			Name:   "てんのもんばん",
			Family: common.Family_Material,
			Rank:   common.Rank_A,
		},
		{
			ID:     350,
			Name:   "パンドラボックス",
			Family: common.Family_Material,
			Rank:   common.Rank_A,
		},
		{
			ID:     351,
			Name:   "キラーマジンガ",
			Family: common.Family_Material,
			Rank:   common.Rank_S,
		},
		{
			ID:     352,
			Name:   "おおめだま",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     353,
			Name:   "グレムリン",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     354,
			Name:   "シールドこぞう",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     355,
			Name:   "ドラキー",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     356,
			Name:   "ドルイド",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     357,
			Name:   "ピクシー",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     358,
			Name:   "ベビーマジシャン",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     359,
			Name:   "メーダ",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     360,
			Name:   "モーモン",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     361,
			Name:   "リップス",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     362,
			Name:   "リリパット",
			Family: common.Family_Demon,
			Rank:   common.Rank_G,
		},
		{
			ID:     363,
			Name:   "おにこぞう",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     364,
			Name:   "くものきょじん",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     365,
			Name:   "くらやみハーピー",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     366,
			Name:   "ごろつき",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     367,
			Name:   "コンジャラー",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     368,
			Name:   "シーメーダ",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     369,
			Name:   "デザートデーモン",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     370,
			Name:   "びっくりサタン",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     371,
			Name:   "ベビーサタン",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     372,
			Name:   "マーマン",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     373,
			Name:   "ランドセーラー",
			Family: common.Family_Demon,
			Rank:   common.Rank_F,
		},
		{
			ID:     374,
			Name:   "オーガー",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     375,
			Name:   "きめんどうし",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     376,
			Name:   "サイクロプス",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     377,
			Name:   "サタンフーラー",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     378,
			Name:   "スイーツまじん",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     379,
			Name:   "スペクテット",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     380,
			Name:   "どくやずきん",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     381,
			Name:   "ひとつめピエロ",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     382,
			Name:   "ベレス",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     383,
			Name:   "メイジドラキー",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     384,
			Name:   "サイレス",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     385,
			Name:   "シャドーサタン",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     386,
			Name:   "シルバーデビル",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     387,
			Name:   "ピサロのてさき",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     388,
			Name:   "ブチュチュンパ",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     389,
			Name:   "ヘルビースト",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     390,
			Name:   "ボストロール",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     391,
			Name:   "ミニデーモン",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     392,
			Name:   "よろいのきし",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     393,
			Name:   "ランプのまじん",
			Family: common.Family_Demon,
			Rank:   common.Rank_D,
		},
		{
			ID:     394,
			Name:   "アンクルホーン",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     395,
			Name:   "じごくのもんばん",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     396,
			Name:   "ずしおうまる",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     397,
			Name:   "タイムマスター",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     398,
			Name:   "デスペクテル",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     399,
			Name:   "てっきゅうまじん",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     400,
			Name:   "ドラキーマ",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     401,
			Name:   "ネクロバルサ",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     402,
			Name:   "ピサロナイト",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     403,
			Name:   "ブルーイーター",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     404,
			Name:   "レッドイーター",
			Family: common.Family_Demon,
			Rank:   common.Rank_C,
		},
		{
			ID:     405,
			Name:   "アークデーモン",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     406,
			Name:   "アークマージ",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     407,
			Name:   "あくましんかん",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     408,
			Name:   "おにこんぼう",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     409,
			Name:   "ギガンテス",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     410,
			Name:   "キラージャック",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     411,
			Name:   "セルゲイナス",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     412,
			Name:   "トロルボンバー",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     413,
			Name:   "ホラービースト",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     414,
			Name:   "ライオネック",
			Family: common.Family_Demon,
			Rank:   common.Rank_B,
		},
		{
			ID:     415,
			Name:   "アトラス",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     416,
			Name:   "ギガデーモン",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     417,
			Name:   "ギュメイ将軍",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     418,
			Name:   "ゲルニック将軍",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     419,
			Name:   "ゴレオン将軍",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     420,
			Name:   "しにがみのきし",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     421,
			Name:   "スカイシーカー",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     422,
			Name:   "バズズ",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     423,
			Name:   "バルザック",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     424,
			Name:   "ベリアル",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     426,
			Name:   "エビルプリースト",
			Family: common.Family_Demon,
			Rank:   common.Rank_S,
		},
		{
			ID:     427,
			Name:   "邪神の子",
			Family: common.Family_Demon,
			Rank:   common.Rank_S,
		},
		{
			ID:     425,
			Name:   "ヘルバトラー",
			Family: common.Family_Demon,
			Rank:   common.Rank_A,
		},
		{
			ID:     428,
			Name:   "アニマルゾンビ",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     429,
			Name:   "おばけキノコ",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     430,
			Name:   "おばけキャンドル",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     431,
			Name:   "がいこつ",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     432,
			Name:   "きりかぶおばけ",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     433,
			Name:   "ゴースト",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     434,
			Name:   "スキッパー",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     435,
			Name:   "ドロル",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     436,
			Name:   "ホイップゴースト",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     437,
			Name:   "メラゴースト",
			Family: common.Family_Undead,
			Rank:   common.Rank_G,
		},
		{
			ID:     438,
			Name:   "おばけヒトデ",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     439,
			Name:   "くさった死体",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     440,
			Name:   "さまようよろい",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     441,
			Name:   "シャドー",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     442,
			Name:   "スカルライダー",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     443,
			Name:   "ふゆうじゅ",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     444,
			Name:   "マドハンド",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     445,
			Name:   "ミイラおとこ",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     446,
			Name:   "やみしばり",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     447,
			Name:   "わかめ王子",
			Family: common.Family_Undead,
			Rank:   common.Rank_F,
		},
		{
			ID:     448,
			Name:   "きつねび",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     449,
			Name:   "しのどれい",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     450,
			Name:   "しりょうのきし",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     451,
			Name:   "じんめんじゅ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     452,
			Name:   "チョコホイップ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     453,
			Name:   "デスマエストロ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     454,
			Name:   "ベロベロ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     455,
			Name:   "ぼうれい剣士",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     456,
			Name:   "マタンゴ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     457,
			Name:   "マネマネ",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     458,
			Name:   "メイデンドール",
			Family: common.Family_Undead,
			Rank:   common.Rank_E,
		},
		{
			ID:     459,
			Name:   "エビルスピリッツ",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     460,
			Name:   "がいこつけんし",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     461,
			Name:   "タタリ御前",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     462,
			Name:   "ナイトウォーカー",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     463,
			Name:   "なげきの亡霊",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     464,
			Name:   "ブラッドハンド",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     465,
			Name:   "ポイズンゾンビ",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     466,
			Name:   "ボーンナイト",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     467,
			Name:   "ほねリーダー",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     468,
			Name:   "ポムポムボム",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     469,
			Name:   "メトロゴースト",
			Family: common.Family_Undead,
			Rank:   common.Rank_D,
		},
		{
			ID:     470,
			Name:   "ウドラー",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     471,
			Name:   "サンダーシャウト",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     472,
			Name:   "しにがみ",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     473,
			Name:   "ソイソルジャー",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     474,
			Name:   "ソードファントム",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     475,
			Name:   "デュラハーン",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     476,
			Name:   "どくろクラゲ",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     477,
			Name:   "ドルマージュ",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     478,
			Name:   "ナイトリッチ",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     479,
			Name:   "ボーンプリズナー",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     480,
			Name:   "黄泉のほのお",
			Family: common.Family_Undead,
			Rank:   common.Rank_C,
		},
		{
			ID:     488,
			Name:   "キラーシャドー",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     481,
			Name:   "しにがみきぞく",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     482,
			Name:   "スカルゴン",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     483,
			Name:   "スモールグール",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     484,
			Name:   "ソードイド",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     485,
			Name:   "デュラハンナイト",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     486,
			Name:   "ドラゴンコープス",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     487,
			Name:   "フェイスボール",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     489,
			Name:   "まおうのつかい",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     490,
			Name:   "メルトア",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     491,
			Name:   "ワイトキング",
			Family: common.Family_Undead,
			Rank:   common.Rank_B,
		},
		{
			ID:     492,
			Name:   "ナイトキング",
			Family: common.Family_Undead,
			Rank:   common.Rank_A,
		},
		{
			ID:     493,
			Name:   "ヘルクラッシャー",
			Family: common.Family_Undead,
			Rank:   common.Rank_A,
		},
		{
			ID:     494,
			Name:   "ホエールロード",
			Family: common.Family_Undead,
			Rank:   common.Rank_A,
		},
		{
			ID:     495,
			Name:   "まおうのかげ",
			Family: common.Family_Undead,
			Rank:   common.Rank_A,
		},
		{
			ID:     496,
			Name:   "バラモスゾンビ",
			Family: common.Family_Undead,
			Rank:   common.Rank_S,
		},
		{
			ID:     497,
			Name:   "カンダタ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_C,
		},
		{
			ID:     498,
			Name:   "バラモス",
			Family: common.Family_Unknown,
			Rank:   common.Rank_A,
		},
		{
			ID:     499,
			Name:   "リーズレット",
			Family: common.Family_Unknown,
			Rank:   common.Rank_A,
		},
		{
			ID:     500,
			Name:   "暗黒神ラプソーン",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     501,
			Name:   "オルゴ・デミーラ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     502,
			Name:   "ゲマ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     503,
			Name:   "シドー",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     504,
			Name:   "邪神ニズゼルファ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     505,
			Name:   "守護者ラズバーン",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     506,
			Name:   "大魔王ウルノーガ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     507,
			Name:   "堕天使エルギオス",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     508,
			Name:   "デスタムーア",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     510,
			Name:   "ドルマゲス",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     511,
			Name:   "ハーゴン",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     512,
			Name:   "ぴぴぼう",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     513,
			Name:   "魔軍司令ホメロス",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     514,
			Name:   "ミルドラース",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     515,
			Name:   "ムドー",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     516,
			Name:   "冥獣王ネルゲル",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     517,
			Name:   "わたぼう",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     518,
			Name:   "ワルぼう",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     509,
			Name:   "デスピサロ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_S,
		},
		{
			ID:     519,
			Name:   "エスターク",
			Family: common.Family_Unknown,
			Rank:   common.Rank_X,
		},
		{
			ID:     520,
			Name:   "神さま",
			Family: common.Family_Unknown,
			Rank:   common.Rank_X,
		},
		{
			ID:     521,
			Name:   "ゾーマ",
			Family: common.Family_Unknown,
			Rank:   common.Rank_X,
		},
		{
			ID:     522,
			Name:   "ダークドレアム",
			Family: common.Family_Unknown,
			Rank:   common.Rank_X,
		},
		{
			ID:     523,
			Name:   "ラーミア",
			Family: common.Family_Unknown,
			Rank:   common.Rank_X,
		},
		{
			ID:     524,
			Name:   "バーガースライム",
			Family: common.Family_Slime,
			Rank:   common.Rank_G,
		},
		{
			ID:     525,
			Name:   "フルーリーサタン",
			Family: common.Family_Demon,
			Rank:   common.Rank_E,
		},
		{
			ID:     526,
			Name:   "バーガーミミック",
			Family: common.Family_Material,
			Rank:   common.Rank_D,
		},
	}
)
